name: 'CI'
on:
  push:
    tags:
      - '*'
  pull_request:

jobs:
  build:
    if: github.event_name  == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mikepenz/action-junit-report@main
        if: endsWith(github.ref, 'main') == false
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          check_name: Example JUnit Test Report
          report_paths: '**/surefire-reports/TEST-*.xml'
      - uses: mikepenz/action-junit-report@main
        if: endsWith(github.ref, 'main') == false
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          check_name: Example Pytest Report
          report_paths: python/report.xml
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-cache-
      - run: npm install
      - run: npm run eslint
      - run: npm run test

  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: "Build Changelog"
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v1
        with:
          configuration: "configs/configuration.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{steps.github_release.outputs.changelog}}
          prerelease: ${{ contains(github.ref, '-rc') || contains(github.ref, '-b') || contains(github.ref, '-a') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

