name: build
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Fyusion/action-surefire-report@main
        if: endsWith(github.ref, 'main') == false
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          check_name: Example Surefire Test Report
      - uses: Fyusion/action-surefire-report@main
        if: endsWith(github.ref, 'main') == false
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          check_name: Example Pytest Report
          report_paths: python/report.xml
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-cache-
      - run: npm install
      - run: npm run eslint
      - run: npm run test
